version: '3'
services:
  mongo-db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - library-app-mongo-db:/data/db
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
  library-app:
    build:
      context: ./library-app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - COUNTER_SERVER_HOST=counter-app
      - COUNTER_SERVER_PORT=3001
      - MONGO_DB_HOST=mongodb://mongo-db:27017/books
    volumes:
      - ./library-app/src:/library-app
  counter-app:
    build:
      context: ./counter-app
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    volumes:
      - ./counter-app/src:/counter-app

volumes:
  library-app-mongo-db:
    driver: local