version: '3'
services:
  library-app:
    build:
      context: ./library-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - COUNTER_SERVER_HOST=counter-app
      - COUNTER_SERVER_PORT=3001
    env_file:
      - .atlas.env
  counter-app:
    build:
      context: ./counter-app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./counter-app/src/db-storage:/counter-app/db-storage
